[project]
name = "skypixelv3"
version = "3.0.0-alpha.1"
description = "A base Disnake bot"
authors = ["RagingEnby <contact@ragingenby.dev>"]
requires-python = ">=3.11"
dependencies = [
    "disnake"
]
